In [2]:
import numpy as np
from ipythonblocks import BlockGrid as bg
from IPython.html.widgets import interact, interactive, fixed
from IPython.html import widgets
from IPython.display import display

:0: FutureWarning: IPython widgets are experimental and may change in the future.


In [22]:
def interacts(f):
    return f
j = interactive(interacts, f = (1,10))
display(j)

In [24]:
y = j.result
print (y)
grid = np.random.choice([0,1,2],size=(y,y),p = [.5,.25,.25])
grid2 = np.hstack(grid)
print (grid,grid2)

8
[[1 2 0 2 0 0 1 0]
 [2 2 0 1 1 2 0 0]
 [2 0 2 0 0 0 0 1]
 [0 0 0 1 1 1 0 0]
 [0 2 0 2 2 0 0 0]
 [0 0 1 0 0 1 0 2]
 [0 0 1 1 0 2 0 0]
 [0 0 0 0 0 2 0 0]] [1 2 0 2 0 0 1 0 2 2 0 1 1 2 0 0 2 0 2 0 0 0 0 1 0 0 0 1 1 1 0 0 0 2 0 2 2
 0 0 0 0 0 1 0 0 1 0 2 0 0 1 1 0 2 0 0 0 0 0 0 0 2 0 0]


In [ ]:
grid1 = bg(y,y)
display(grid1)
def make_grid(c):
    x = 0
    for i in grid1:
        if grid2[x]==1:
            i.set_colors(300, 178, 34)
        elif grid2[x]==2:
            i.set_colors(90, 300, 420)
        x+=1
    print (c)
    return (grid1)

In [13]:
grid = BlockGrid(10, 10)
w = np.linspace(0,8,9)
c = []
d = []
e = []
f = []
k = []
j = []
p = []
q = []
aa = []
bb = []
p2 = []
q2 = []
aa2 = []
bb2 = []
for i in w:
    a = np.random.randint(0, 10)
    b = np.random.randint(0, 10)
    x = np.random.randint(0, 10)
    y = np.random.randint(0, 10)
    s = np.random.randint(0, 10)
    i = np.random.randint(0, 10)
    s1 = np.random.randint(0, 10)
    i1 = np.random.randint(0, 10)
    ss = np.random.randint(0, 10)
    ii = np.random.randint(0, 10)
    ss1 = np.random.randint(0, 10)
    ii1 = np.random.randint(0, 10)
    p.append(s)
    q.append(i)
    aa.append(ss)
    bb.append(ii)
    p2.append(s1)
    q2.append(i1)
    aa2.append(ss1)
    bb2.append(ii1)
    c.append(a)
    d.append(b)
    e.append(x)
    f.append(y)
    g = np.hstack((a,b))
    h = np.hstack((x,y))
    k.append(g)
    j.append(h)
    
cc = np.hstack(aa)
dd = np.hstack(bb)
p1 = np.hstack(p)
q1 = np.hstack(q)
cc2 = np.hstack(aa2)
dd2 = np.hstack(bb2)
p3 = np.hstack(p2)
q3 = np.hstack(q2)
h = np.hstack(c)
l = np.hstack(d)
m = np.hstack(e)
o = np.hstack(f)
print ('h', h) 
print ('l', l) 
print ('m', m)
print ('o', o)
print ('p1', p1)
print ('q1', q1)
print ('cc', cc)
print ('dd', dd)
print ('p3', p3)
print ('q3', q3)
print ('cc2', cc2)
print ('dd2', dd2)
    
r = np.vstack(k)
t = np.vstack(j)
print (r)
print (t)
for n in w:
    if r.any()==r.any()==True and t.any()==t.any()==True:
        for block in grid[p1[n]:p1[n]+1, q1[n]:q1[n]+1]:
            block.blue = 100
        for block in grid[cc[n]:cc[n]+1, dd[n]:dd[n]+1]:
            block.green = 100
    elif h.any()==m.any()==True and l.any()==o.any()==True:
        n.black = 0
        for block in grid[p3[n]:p3[n]+1, q3[n]:q3[n]+1]:
            block.blue = 100
        for block in grid[cc2[n]:cc2[n]+1, dd2[n]:dd2[n]+1]:
            block.green = 100
    else:
        for block in grid[m[n]:m[n]+1, o[n]:o[n]+1]:
            block.blue = 100
        for block in grid[h[n]:h[n]+1, l[n]:l[n]+1]:
            block.green = 100
grid

h [3 6 7 5 4 6 4 8 5]
l [9 3 1 1 5 8 3 7 8]
m [5 5 4 1 2 9 0 8 6]
o [2 4 8 6 5 4 7 9 7]
p1 [8 8 6 9 3 1 8 1 9]
q1 [6 7 4 8 8 3 0 9 7]
cc [3 8 7 0 7 3 8 9 1]
dd [3 9 6 1 0 4 1 7 1]
p3 [9 0 2 6 6 2 5 0 9]
q3 [4 4 1 1 7 1 7 9 2]
cc2 [6 4 5 9 3 3 4 6 6]
dd2 [3 1 2 5 2 5 6 8 4]
[[3 9]
 [6 3]
 [7 1]
 [5 1]
 [4 5]
 [6 8]
 [4 3]
 [8 7]
 [5 8]]
[[5 2]
 [5 4]
 [4 8]
 [1 6]
 [2 5]
 [9 4]
 [0 7]
 [8 9]
 [6 7]]


In [42]:
grid1 = BlockGrid(10, 10)
z = []
y = []
c = 0
d = 0
for block in grid1:
    x = np.random.randint(0,11)
    if x < 3:
        block.set_colors(300, 178, 34)
        y.append(x)
        a = np.hstack(y)
        c+=1
    elif x > 7:
        block.set_colors(90, 300, 420)
        z.append(x)
        b = np.hstack(z)
        d+=1
    else:
        block.set_colors(0, 0, 0)
        
print (c,d)

def satisfied(b)
grid1

30 28


In [4]:
grid = BlockGrid(10, 10)
x = np.random.randint(0, 10)
y = np.random.randint(6, 10)
z = np.random.randint(0, 5)
w = np.linspace (0,5,6)
print (w, x, y, z)
if y >x:
    if y > z:
        for i in w:
            for block in grid[x:y, x:z]:
                block.set_colors(245, 178, 34)
grid

[ 0.  1.  2.  3.  4.  5.] 3 9 0


In [6]:
grid = BlockGrid(10, 10)
for block in grid[1:2, 0:1]:
    block.set_colors(245, 178, 34)
grid

In [125]:
grid = BlockGrid(10, 10)
w = np.linspace(0,5,8)
for i in w:
    a = np.random.randint(0, 10)
    b = np.random.randint(0, 10)
    x = np.random.randint(0, 10)
    y = np.random.randint(0, 10)
    print (a,b,x,y)
    if x==a and y==b:
        block.black = 0
    else:
        for block in grid[x:x+1, y:y+1]:
            block.blue = 100
        for block in grid[a:a+1, b:b+1]:
            block.green = 100
grid

8 9 1 0
5 0 3 2
3 2 9 6
2 5 8 6
5 7 6 0
4 4 4 5
5 4 5 1
8 2 0 5


In [127]:
grid = BlockGrid(10, 10)
w = np.linspace(0,5,8)
c = []
d = []
e = []
f = []
for i in w:
    a = np.random.randint(0, 9)
    b = np.random.randint(0, 9)
    x = np.random.randint(0, 9)
    y = np.random.randint(0, 9)
    c.append(a)
    d.append(b)
    e.append(x)
    f.append(y)
h = np.hstack(c)
k = np.hstack(d)
m = np.hstack(e)
o = np.hstack(f)
print ('h', h) 
print ('k', k) 
print ('m', m)
print ('o', o)
    
for n in w:
    if m.all()==h.all():
        if o[n]==k[n]:
            block.black = 0
    else:
        for block in grid[m[n]:m[n]+1, o[n]:o[n]+1]:
            block.blue = 100
        for block in grid[h[n]:h[n]+1, k[n]:k[n]+1]:
            block.green = 100
grid

h [2 8 4 8 5 8 1 5]
k [3 6 7 3 4 3 6 3]
m [3 5 7 1 6 7 1 1]
o [2 7 1 3 0 1 8 2]


In [147]:
grid = BlockGrid(10, 10)
w = np.linspace(0,8,9)
c = []
d = []
e = []
f = []
k = []
j = []
for i in w:
    a = np.random.randint(0, 10)
    b = np.random.randint(0, 10)
    x = np.random.randint(0, 10)
    y = np.random.randint(0, 10)
    c.append(a)
    d.append(b)
    e.append(x)
    f.append(y)
    g = np.hstack((a,b))
    h = np.hstack((x,y))
    k.append(g)
    j.append(h)
    
h = np.hstack(c)
l = np.hstack(d)
m = np.hstack(e)
o = np.hstack(f)
print ('h', h) 
print ('l', l) 
print ('m', m)
print ('o', o)
    
r = np.vstack(k)
t = np.vstack(j)
print (r)
print (t)
for n in w:
    if r[n]==r.any==True and t[n]==t.any()==True:
        block.black = 0
        for block in grid[m[n]-1:m[n], o[n]-1:o[n]]:
            block.blue = 100
        for block in grid[h[n]-1:h[n], l[n]-1:l[n]]:
            block.green = 100
    elif h[n]==m.any==True and l[n]==o.any()==True:
        block.black = 0
        for block in grid[m[n]+1:m[n]+2, o[n]+1:o[n]+2]:
            block.blue = 100
        for block in grid[h[n]+1:h[n]+2, l[n]+1:l[n]+2]:
            block.green = 100
    else:
        for block in grid[m[n]:m[n]+1, o[n]:o[n]+1]:
            block.blue = 100
        for block in grid[h[n]:h[n]+1, l[n]:l[n]+1]:
            block.green = 100
grid

h [8 9 8 6 7 2 6 2 5]
l [8 1 2 1 0 2 7 5 8]
m [2 7 6 0 6 4 8 7 0]
o [2 2 8 9 0 6 2 0 2]
[[8 8]
 [9 1]
 [8 2]
 [6 1]
 [7 0]
 [2 2]
 [6 7]
 [2 5]
 [5 8]]
[[2 2]
 [7 2]
 [6 8]
 [0 9]
 [6 0]
 [4 6]
 [8 2]
 [7 0]
 [0 2]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [9]:
grid = BlockGrid(10, 10)
a = np.random.randint(10, size = 10)
b = np.random.randint(10, size = 10)
x = np.random.randint(10, size = 10)
y = np.random.randint(10, size = 10)
print (a,b,x,y)
w = np.linspace(0,5,11)
for i in w:
    if x[i]==a[i] and y[i]==b[i]:
        block.black = 0
    else:
        for block in grid[x:x+1, y:y+1]:
            block.blue = 100
        for block in grid[a:a+1, b:b+1]:
            block.green = 100
    i+=1
grid

[3 9 3 8 2 3 6 5 2 4] [8 1 0 2 4 8 7 6 5 2] [2 9 0 6 8 5 7 8 0 0] [5 0 8 1 2 0 4 1 6 0]


TypeError: only integer arrays with one element can be converted to an index

In [118]:
N = BlockGrid(4,4)
for i in N:
    x = np.random.randint(1, 5)
    y = np.random.randint(1, 5)
    print (x,y)
    if i.row == x or i.col== y:
        i.green = 100
    elif i.col == y or i.col== x:
        i.red = 100
N

3 3
1 1
3 1
4 3
1 4
2 3
3 3
3 1
3 3
4 1
4 3
2 4
3 1
2 1
2 2
2 3


In [440]:
N = BlockGrid(4,4)
for i in N:
    x = np.random.randint(1, 5)
    y = np.random.randint(1, 5)
    print (x,y)
    if i.row == x:
        x+=1
        i.green = 100
        for m in np.linspace(0,2,x):
            print (m)
            if i.row == x:
                i.blue = 100
    elif i.col == x+1 and i.row == x+1:
        i.red = 100
N

4 1
1 4
3 3
4 3
4 1
3 3
4 4
1 3
0.0
2.0
3 2
1 4
2 1
0.0
1.0
2.0
4 3
1 1
2 1
1 2
3 1
0.0
0.666666666667
1.33333333333
2.0
