In [4]:
import numpy as np
from ipythonblocks import BlockGrid as bg
from IPython.html.widgets import interact, interactive, fixed
from IPython.html import widgets
from IPython.display import display

:0: FutureWarning: IPython widgets are experimental and may change in the future.


In [5]:
def interacts(size):
    return size
def interacts1(satisfaction_percent_1):
    return satisfaction_percent_1
def interacts2(orange_percent):
    return orange_percent
def interacts3(blue_percent):
    return blue_percent
j = interactive(interacts, size = (1,20))
p = interactive(interacts1, satisfaction_percent_1 = (0,1,0.01))
o1 = interactive(interacts2, orange_percent = (0,1,0.01))
b1 = interactive(interacts3, blue_percent = (0,1,0.01))
display(j)
display(p)
display(b1)
display(o1)

In [6]:
k = j.result
satisfaction_percent = p.result
blue = b1.result
orange = o1.result
black = 1 - blue - orange
print (black)
y = k - 1
grid = np.random.choice([0,1,2],size=(k,k),p = [.34,.33,.33])
print (grid)
grid2 = np.hstack(grid)
grid1 = bg(k,k)


1.0
[[0 1 0 2 0 1 1 2 1 2]
 [2 1 0 0 0 0 2 0 0 0]
 [0 2 2 2 1 1 1 1 1 1]
 [1 0 1 2 1 2 2 1 2 0]
 [0 1 2 2 1 0 1 0 0 1]
 [0 2 1 0 2 2 2 2 2 1]
 [1 1 2 1 1 1 2 0 2 0]
 [0 1 1 1 2 1 2 1 0 2]
 [1 1 1 0 1 0 0 0 2 1]
 [0 2 1 0 1 0 0 1 2 1]]


In [7]:
def make_grid():
    x = 0
    for i in grid1:
        if grid2[x]==1:
            i.set_colors(300, 178, 34)
        elif grid2[x]==2:
            i.set_colors(90, 300, 420)
        x+=1
    display(grid1)
make_grid()

In [8]:
def satisfaction_percent():
    same_c1 = 0
    same_c2 = 0
    same_c3 = 0
    same_c4 = 0
    same_col_1 = 0
    same_col_2 = 0
    same_row_1 = 0
    same_row_2 = 0
    sat_col_1=[] 
    sat_col_2=[] 
    sat_row_1=[] 
    sat_row_2=[] 
    sat_1=[] 
    same = 0
    row = 0
    col = 0
    i_5 = 0
    i_6 = 0
    i_7 = 0
    i_8 = 0
    i_9 = 0
    for n in grid:
        if row==0 and col==0:
            if grid[0,0]==0:
                same_c1+=0
            else:
                if grid[0,0]==grid[1,0]:
                    same_c1+=1
                if grid[0,0]==grid[0,1]:
                    same_c1+=1
                if grid[0,0]==grid[1,1]:
                    same_c1+=1
            satisfaction_c1 = same_c1/3
            print ('satisfaction_c1', satisfaction_c1)
        elif row==0 and col==y:
            if grid[0,y]==0:
                same_c2+=0
            else:
                if grid[0,y]==grid[0,y-1]:
                    same_c2+=1
                if grid[0,y]==grid[1,y-1]:
                    same_c2+=1
                if grid[0,y]==grid[1,y]:
                    same_c2+=1
            satisfaction_c2 = same_c2/3
            print ('satisfaction_c2',satisfaction_c2)
        elif row==y and col==0:
            if grid[y,0]==0:
                same_c3+=0
            else:
                if grid[y,0]==grid[y-1,0]:
                    same_c3+=1
                if grid[y,0]==grid[y-1,1]:
                    same_c3+=1
                if grid[y,0]==grid[y,1]:
                    same_c3+=1
            satisfaction_c3 = same_c3/3
            print ('satisfaction_c3',satisfaction_c3)
        elif row==y and col==y:
            if grid[y,y]==0:
                same_c4+=0
            else:
                if grid[y,y]==grid[y-1,y]:
                    same_c4+=1
                if grid[y,y]==grid[y,y-1]:
                    same_c4+=1
                if grid[y,y]==grid[y-1,y-1]:
                    same_c4+=1
            satisfaction_c4 = same_c4/3
            print ('satisfaction_c4', satisfaction_c4)
        elif row==0 and col!=(0 or y):
            i_5+=1
            if grid[row,col]==0:
                same_col_1+=0
            else:
                if grid[row,col]==grid[row,col-1]:
                    same_col_1+=1
                if grid[row,col]==grid[row,col+1]:
                    same_col_1+=1
                if grid[row,col]==grid[row+1,col-1]:
                    same_col_1+=1
                if grid[row,col]==grid[row+1,col]:
                    same_col_1+=1
                if grid[row,col]==grid[row+1,col+1]:
                    same_col_1+=1
            satisfaction_col_1 = same_col_1/5
            sat_col_1.append(satisfaction_col_1)
            true_satisfaction_col_1 = np.hstack(sat_col_1) 
            if i_5>y-1:
                sat_col_1 = true_satisfaction_col_1
                print ('sat_col_1',sat_col_1)

        elif row==y and col!=(0 or y):
            i_6+=1
            if grid[row,col]==0:
                same_col_2+=0
            else:
                if grid[row,col]==grid[row,col-1]:
                    same_col_2+=1
                if grid[row,col]==grid[row,col+1]:
                    same_col_2+=1
                if grid[row,col]==grid[row-1,col-1]:
                    same_col_2+=1
                if grid[row,col]==grid[row-1,col]:
                    same_col_2+=1
                if grid[row,col]==grid[row-1,col+1]:
                    same_col_2+=1
            satisfaction_col_2 = same_col_2/5
            sat_col_2.append(satisfaction_col_2)
            true_satisfaction_col_2 = np.hstack(sat_col_2) 
            if i_6>y-1:
                sat_col_2 = true_satisfaction_col_2
                print ('sat_col_2',sat_col_2)
        elif row!=(0 or y) and col==0:
            i_7+=1
            if grid[row,col]==0:
                same_row_1+=0
            else:
                if grid[row,col]==grid[row-1,col]:
                    same_row_1+=1
                if grid[row,col]==grid[row+1,col]:
                    same_row_1+=1
                if grid[row,col]==grid[row-1,col+1]:
                    same_row_1+=1
                if grid[row,n]==grid[row,col+1]:
                    same_row_1+=1
                if grid[row,col]==grid[row+1,col+1]:
                    same_row_1+=1
            satisfaction_row_1 = same_row_1/5
            sat_row_1.append(satisfaction_row_1)
            true_satisfaction_row_1 = np.hstack(sat_row_1) 
            if i_7>y-1:
                sat_row_1 = true_satisfaction_row_1
                print ('sat_row_1',sat_row_1)
        elif row!=(0 or y) and col==y:
            i_8+=1
            if grid[row,col]==0:
                same_row_2+=0
            else:
                if grid[row,col]==grid[row-1,col]:
                    same_row_2+=1
                if grid[row,col]==grid[row+1,col]:
                    same_row_2+=1
                if grid[row,col]==grid[row-1,col-1]:
                    same_row_2+=1
                if grid[row,col]==grid[row,col-1]:
                    same_row_2+=1
                if grid[row,col]==grid[row+1,col-1]:
                    same_row_2+=1
            satisfaction_row_2 = same_row_2/5
            sat_row_2.append(satisfaction_row_2)
            true_satisfaction_row_2 = np.hstack(sat_row_2) 
            if i_8>y-1:
                sat_row_2 = true_satisfaction_row_2
                print ('sat_row_2',sat_row_2)
        else:
            i_9+=1
            if grid[row,col]==0:
                same+=0
            else:
                if grid[row,col]==grid[row-1,col]:
                    same+=1
                if grid[row,col]==grid[row,col-1]:
                    same+=1
                if grid[row,col]==grid[row-1,col-1]:
                    same+=1
                if grid[row,col]==grid[row+1,col]:
                    same+=1
                if grid[row,col]==grid[row,col+1]:
                    same+=1
                if grid[row,col]==grid[row+1,col+1]:
                    same+=1
                if grid[row,col]==grid[row-1,col+1]:
                    same+=1
                if grid[row,col]==grid[row+1,col-1]:
                    same+=1
            satisfaction = same/8
            sat_1.append(satisfaction)
            true_satisfaction_1 = np.hstack(sat_1) 
            if i_9>y-2:
                sat_1 = true_satisfaction_1
                print ('sat_1',sat_1)
        col+=1
        if col>=10:
            col = col - 10
            row+=1
    
    sat_c_1_1 = []
    sat_c_2_1 = []
    sat_c_3_1 = []
    sat_c_4_1 = []
    sat_col_1_1 = []
    sat_col_2_1 = []
    sat_row_1_1 = []
    sat_row_2_1 = []
    sat_1_1 = []
    m_1=0
    m_2=0
    m_3=0
    m_4=0
    m_5=0
    m_6=0
    m_7=0
    m_8=0
    m_9=0
    
    for n in sat_col_1:
        if m_5==0:
            new_value_5 = sat_col_1[0]
            sat_col_1_1.append(new_value_5)
            s_col_1 = np.hstack(sat_col_1_1)
        else:
            new_value_5 = sat_col_1[m_5] - sat_col_1[m_5-1]
            sat_col_1_1.append(new_value_5)
        m_5+=1     
    
    for n in sat_col_2:
        if m_6==0:
            new_value_6 = sat_col_2[0]
            sat_col_2_1.append(new_value_6)
            s_col_2 = np.hstack(sat_col_2_1)
            print (new_value_6)
        else:
            new_value_6 = sat_col_2[m_6] - sat_col_2[m_6-1]
            sat_col_2_1.append(new_value_6)
        m_6+=1 
        
    for n in sat_row_1:
        if m_7==0:
            new_value_7 = sat_row_1[0]
            sat_row_1_1.append(new_value_7)
            sat_row_1 = np.hstack(sat_row_1_1)
        else:
            new_value_7 = sat_row_1[m_7] - sat_row_1[m_7-1]
            sat_row_1_1.append(new_value_7)
        m_7+=1 
    for n in sat_row_2:
        if m_8==0:
            new_value_8 = sat_row_2[0]
            sat_row_2_1.append(new_value_8)
            s_row_2 = np.hstack(sat_row_2_1)
        else:
            new_value_8 = sat_row_2[m_8] - sat_row_2[m_8-1]
            sat_row_2_1.append(new_value_8)
        m_8+=1 
        
    for n in sat_1:
        if m_9==0:
            new_value_9 = sat_1[0]
            sat_1_1.append(new_value_9)
            sat_1 = np.hstack(sat_1_1)
        else:
            new_value_9 = sat_1[m_9] - sat_1[m_9-1]
            sat_1_1.append(new_value_9)
        m_9+=1 
        
        
    s_col_1 = np.hstack(sat_col_1_1)
    #s_col_2 = np.hstack(sat_col_2_1)
    #s_row_1 = np.hstack(sat_row_1_1)
    #s_row_2 = np.hstack(sat_row_2_1)
    #s_1 = np.hstack(sat_1_1)

    print ('s_col_1',s_col_1)
    #print ('s_col_2',s_col_2)
    #print ('s_row_1',s_row_1)
    #print ('s_row_2',s_row_2)
    #print ('s_1',s_1)
    return (satisfaction_c1,satisfaction_c2,satisfaction_c3,satisfaction_c4,s_col_1,s_col_2,s_row_1,s_row_2,s_1)

In [10]:
satisfaction_percent()

satisfaction_c1 0.0
satisfaction_c2 0.0
s_col_1 [ 0.2  0.   0.   0.   0.2  0.2  0.2  0. ]


UnboundLocalError: local variable 'satisfaction_c3' referenced before assignment

In [ ]:
def make_grid(y):
    grid = np.random.choice([0,1,2],size=(y,y),p = [.5,.25,.25])
    grid2 = np.hstack(grid)
    print (grid2)
    grid1 = bg(y,y)
    x = 0
    for i in grid1:
        if grid2[x]==1:
            i.set_colors(300, 178, 34)
        elif grid2[x]==2:
            i.set_colors(90, 300, 420)
        x+=1
        print (y)
    return grid1

In [ ]:
interact(make_grid, y = )

In [2]:
grid = BlockGrid(10, 10, fill=(1, 1, 1))
grid

In [3]:
grid[0, 0]

Block(1, 1, 1, size=20)

In [4]:
np.random.random_integers(0.0, 10)

7

In [5]:
N = np.linspace(0, 5, 6)
print (N)

[ 0.  1.  2.  3.  4.  5.]


In [6]:
grid = BlockGrid(10, 10)
a = np.random.randint(10, size = 10)
b = np.random.randint(10, size = 10)
x = np.random.randint(10, size = 10)
y = np.random.randint(10, size = 10)
print (a,b,x,y)
for block in grid:
    if x.any()==a.any() and y.any()==b.any():
        block.black = 0
    else:
        for block in grid[x:x+1, y:y+1]:
            block.blue = 100
        for block in grid[a:a+1, b:b+1]:
            block.green = 100
grid

[1 6 3 0 0 3 4 8 6 9] [6 1 3 1 1 0 8 9 1 1] [7 7 4 0 9 6 1 8 3 0] [7 9 9 8 9 2 2 0 2 3]


In [7]:
grid = BlockGrid(10, 10)
a = np.random.randint(10, size = 10)
b = np.random.randint(10, size = 10)
x = np.random.randint(10, size = 10)
y = np.random.randint(10, size = 10)
print (a,b,x,y)

if x.any()==a.any() and y.any()==b.any():
    block.black = 0
elif a.any()==a.any() and b.any()==b.any():
    block.black = 0
elif x.any()==x.any() and y.any()==y.any():
    block.black = 0
else:
    for block in grid[x:x+1, y:y+1]:
        block.blue = 100
    for block in grid[a:a+1, b:b+1]:
        block.green = 100
        
        
grid

[1 5 2 7 8 6 3 9 9 4] [3 2 0 1 1 5 1 7 8 0] [2 9 3 7 7 4 2 6 1 7] [1 1 8 0 2 5 3 6 1 3]


In [8]:
for i in N:
    x = np.random.randint(9)
    y = np.random.randint(9)
    print (x, y)
    for block in grid:
        if block.row == x and block.col == y:
            block.green = 100
        elif block.row == x or block.col == y:
            block.green = 1000
        else:
            block.green = 0
            
grid

6 0
4 6
2 0
2 5
8 3
1 2
