# Numpy Exercise 1

## Imports

In [23]:
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
import antipackage
import github.ellisonbg.misc.vizarray as va

## Checkerboard

Write a Python function that creates a square `(size,size)` 2d Numpy array with the values `0.0` and `1.0`:

* Your function should work for both odd and even `size`.
* The `0,0` element should be `1.0`.
* The `dtype` should be `float`.

In [131]:
#Got online help on syntax for how to insert a number into a given row/column. 
def checkerboard(size):
    a = np.ones((size,size),dtype=float)
    a[::2,1::2] = 0
    a[1::2,::2] = 0
    print a

checkerboard(6)

[[ 1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.]]


In [130]:
a = checkerboard(4)
assert a[0,0]==1.0
assert a.sum()==8.0
assert a.dtype==np.dtype(float)
assert np.all(a[0,0:5:2]==1.0)
assert np.all(a[1,0:5:2]==0.0)

b = checkerboard(5)
assert b[0,0]==1.0
assert b.sum()==13.0
assert np.all(b.ravel()[0:26:2]==1.0)
assert np.all(b.ravel()[1:25:2]==0.0)

[[ 1.  0.  1.  0.]
 [ 0.  1.  0.  1.]
 [ 1.  0.  1.  0.]
 [ 0.  1.  0.  1.]]


TypeError: 'NoneType' object has no attribute '__getitem__'

Use `vizarray` to visualize a checkerboard of `size=20` with a block size of `10px`.

In [170]:
import antipackage
import github.ellisonbg.misc.vizarray as va

import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
va.enable()

In [171]:
def checkerboard(size):
    a = np.ones((size,size),dtype=float)
    a[::2,1::2] = 0
    a[1::2,::2] = 0
    print a
    va.vizarray(a)
    
va.enable()
checkerboard(20)
vizarray.set_block_size(10)

[[ 1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.
   1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.
   0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.
   1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.
   0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.
   1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.
   0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.
   1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.
   0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.
   1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.
   0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.
   1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.

NameError: name 'vizarray' is not defined

In [28]:
assert True

Use `vizarray` to visualize a checkerboard of `size=27` with a block size of `5px`.

In [172]:
def checkerboard(size):
    a = np.ones((size,size),dtype=float)
    a[::2,1::2] = 0
    a[1::2,::2] = 0
    print a
    va.vizarray(a)
    
va.enable()
checkerboard(27)
vizarray.set_block_size(5)

[[ 1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.
   1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.
   0.  1.  0.  1.  0.  1.  0.  1.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.
   1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.
   0.  1.  0.  1.  0.  1.  0.  1.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.
   1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.
   0.  1.  0.  1.  0.  1.  0.  1.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.
   1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.
   0.  1.  0.  1.  0.  1.  0.  1.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.
   1.  0.  1.  0.  1. 

NameError: name 'vizarray' is not defined

In [164]:
assert True